### ISSUE TITLE
Feature request: Display token count when generating text files

### ISSUE THREAD

**Issue by doggy8088** [abinthomasonline/repo2txt#12]
Is it possible to display token count when generating text files?

**Comment by abinthomasonline** [comment]
Great suggestion—this would be a helpful addition! 

There are two ways we could implement it: a rough estimate using the rule of 4 characters ≈ 1 token, or by using a library like [gpt-tokenizer](https://www.npmjs.com/package/gpt-tokenizer) for more accurate counting. 

Do you think it's worth adding this library and loading its vocabulary for the extra precision?

**Comment by abinthomasonline** [comment]
Added this https://github.com/abinthomasonline/repo2txt/commit/bf663e796043bd79bc16e2468a6f877590d5c8c1

@doggy8088 Thanks!
