### ISSUE TITLE
API functionality

### ISSUE THREAD

**Issue by daedalus-s** [abinthomasonline/repo2txt#3]
Please add a feature to the existing system that would expose the service as an API and download the output file into an output directory of choice. I can help with the development of this feature. Contact me at sreenikethaathreya@gmail.com.

**Comment by abinthomasonline** [comment]
I'm not looking to set up a server. Is there a way to do it without one?

**Comment by daedalus-s** [comment]
Okay no problem, will figure something out on my own. Thanks!
